---
- name: Install PostgreSQL server and client
  apt:
    name:
      - postgresql
      - postgresql-contrib
      - python3-psycopg2
    state: present

- name: Create database user
  community.postgresql.postgresql_user:
    name: "{{ postgres_user }}"
    password: "{{ postgres_password }}"
    role_attr_flags: CREATEDB,NOSUPERUSER
  become_user: postgres

- name: Create database
  community.postgresql.postgresql_db:
    name: "{{ postgres_db }}"
    owner: "{{ postgres_user }}"
  become_user: postgres
